baseURL = 'https://pyska-ratzinger.github.io/'
#baseURL = 'http://localhost:8080/'
languageCode = 'en-us'
title = "PysKa's Writeups"
theme = "pyska_eyes"

disqusShortname = 'pyskaratzinger'
buildDrafts = false

[author]
	name = "PysKa Ratzinger"
	email = "ricardojorge512@hotmail.com"

[params]
	description = "A blog with writeup's or something. Idk. It's probably boring."

	colortheme = "dark"

	mainSection = "posts"
	postsOnHomepage = 5
	tagsOverview = true

	show_updated = true
	showReadTime = true

	[params.meta]
		favicon = false

	[params.comments]
		enabled = true
		engine = "disqus"

[privacy]
	[privacy.disqus]
		disable = true
	[privacy.googleAnalytics]
		anonymizeIP = true
		disable = true
		respectDoNotTrack = true
		useSessionStorage = true
	[privacy.instagram]
		disable = true
		simple = true
	[privacy.twitter]
		disable = true
		enableDNT = true
		simple = true
	[privacy.vimeo]
		disable = true
		enableDNT = true
		simple = true
	[privacy.youtube]
		disable = true
		privacyEnhanced = true


[markup]
	[markup.highlight]
		anchorLineNos = false
		codeFences = true
		guessSyntax = false
		hl_Lines = ''
		hl_inline = false
		lineAnchors = ''
		lineNoStart = 1
		lineNos = false
		lineNumbersInTable = true
		noClasses = true
		style = 'gruvbox'
		tabWidth = 4
		wrapperClass = 'highlight'


[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "All posts"
	url = "/posts"
	weight = 2

[[menu.main]]
	name = "Categories"
	url = "/categories"
	weight = 3

[[menu.main]]
	name = "Tags"
	url = "/tags"
	weight = 4

[[menu.main]]
	name = "About"
	url = "/about"
	weight = 5

[[menu.social]]
    name = "GitHub"
    url = "https://github.com/PysKa-Ratzinger/"
    pre = "<i class='fab fa-github'>Github</i>"
	weight = 1

